DAYD-659 ACT-PLN-PlanCreateAfterSchedule_予定/TODO登録（スケジュール後）
daydule/backend pull request #21
Opened 2022-11-28 14:12 UTC by Mellbrother

# 事前確認

-   [ ] PR前に動作確認をしたか
-   [ ] ビルドエラー/ESLintエラーは起きていないか
-   [ ] [開発ルール](https://daydule.atlassian.net/wiki/spaces/DAYDULE/pages/9765029)を守って実装しているか
-   [ ] 単体テストが全てOKになっているか
-   [ ] 機密情報を含んでいないか
-   [ ] 最新の`develop`ブランチを反映しているか

# やったこと

# やらないこと

# 懸念点や注意点

# その他

2022-12-13 08:07 UTC, tom-takeru requested changes
コメントした！

2022-12-13 08:07 UTC, tom-takeru commented on postgres/src/01_ddl/1006_create_table_temporary_plans.sql
> +  "is_delete"        BOOLEAN             NOT NULL DEFAULT false,
is_deletedがいいな

2022-12-13 08:07 UTC, tom-takeru commented on postgres/src/01_ddl/1006_create_table_temporary_plans.sql
> +  "original_plan_id" INTEGER      UNIQUE     NULL REFERENCES "plans" ("id"),
```
  "original_plan_id" INTEGER      UNIQUE     NULL REFERENCES "plans" ("id"),
```

NULLだけ残すと、どんな制約になるの？それか、消し忘れ？

2022-12-29 08:25 UTC, Mellbrother commented on postgres/src/01_ddl/1006_create_table_temporary_plans.sql
> +  "original_plan_id" INTEGER      UNIQUE     NULL REFERENCES "plans" ("id"),
必要ないから削除した

2022-12-29 08:25 UTC, Mellbrother commented on postgres/src/01_ddl/1006_create_table_temporary_plans.sql
> +  "is_delete"        BOOLEAN             NOT NULL DEFAULT false,
修正した

2023-01-09 09:38 UTC, tom-takeru approved these changes

2023-01-09 09:38 UTC, merged