add シンプルスケジュール作成ロジック実装
daydule/backend pull request #23
Opened 2023-01-02 20:22 UTC by Mellbrother

# 事前確認

-   [ ] PR前に動作確認をしたか
-   [ ] ビルドエラー/ESLintエラーは起きていないか
-   [ ] [開発ルール](https://daydule.atlassian.net/wiki/spaces/DAYDULE/pages/9765029)を守って実装しているか
-   [ ] 単体テストが全てOKになっているか
-   [ ] 機密情報を含んでいないか
-   [ ] 最新の`develop`ブランチを反映しているか

# やったこと

# やらないこと

# 懸念点や注意点

# その他

2023-01-09 09:41 UTC, tom-takeru commented on app/utils/time.js
> + *  予定の開始時間・終了時間を計算する
これはutilなのか？

2023-01-09 09:42 UTC, tom-takeru commented on package.json
> +    "proxyquire": "^2.1.3",
これはなんのライブラリ？

2023-01-09 09:44 UTC, tom-takeru commented on app/helpers/schedule/simpleScheduleHelper.js
> +    // TODO: バリデーション
ヘルパーはアクションから呼ぶからバリデーションはアクションの方で済んでると思って良いんじゃないかな？

2023-01-09 09:51 UTC, tom-takeru commented on app/utils/time.js
> + * @returns {number} - 開始時間、終了時間
オブジェクトの場合はこう書くっぽい
```
~略
@returns {Object} result - オブジェクト
@returns {number} result.startTime - 開始時間
@returns {number} result.endTime- 終了時間
~略
```

参考：https://qiita.com/zaburo/items/c90ab1a3d7751f610d27#%E5%BF%9C%E7%94%A8%EF%BC%92object%E3%82%92%E8%A8%98%E8%BF%B0%E3%81%99%E3%82%8B

2023-01-09 11:33 UTC, tom-takeru requested changes
いっぱいコメントしてしまった。
申し訳ないけど、確認お願いします🙏

2023-01-09 11:33 UTC, tom-takeru commented on app/config/const.js
> +    SECTION_MINUTES_LENGTH: 5,
[スケジュール参照のとこの定数定義](https://github.com/daydule/backend/pull/15/files#diff-53d536be4750e7ae90a741a3de285944eb2630baf06179d4059070b5707879f7)↓に合わせて、`simpleScheduleHelper`がキーのオブジェクトにした方がわかりやすくない？
```JavaScript
    PLAN_TYPE: {
        PLAN: 0,
        FIX_PLAN: 1,
        TODO: 2
    }
```

2023-01-09 11:33 UTC, tom-takeru commented on app/config/const.js
> +    SECTION_MINUTES_LENGTH: 5,
実装的には元の方がアクセスがよさそうだね、、、。
やっぱどっちでも良いや。でも元のままの場合は配列でもよさそう？

`PLAN_TYPE`の記法に合わせた場合のキーの探し方はこんな感じ。
```
const FRUIT = {
  'Apple': 'りんご',
  'Grape': 'ぶどう',
  'Strawberry': 'いちご'
}

const key = Object.keys(FRUIT).find((key) => FRUIT[key] === 'ぶどう')
console.log(key) // Grape
```

2023-01-09 11:33 UTC, tom-takeru commented on app/utils/time.js
> +        now.getDate(),
```
        now.getFullYear(),
        now.getMonth(),
        now.getDate(),
```
この３つ一応変数に置いた方が良いと思う

2023-01-09 11:33 UTC, tom-takeru commented on app/utils/time.js
> + * @returns {number} - 比較結果
単位が欲しい
分だよね？

2023-01-09 11:33 UTC, tom-takeru commented on app/helpers/schedule/simpleScheduleHelper.js
> +    let freeTime = new Array(timeUtil.subtractTimeStr(endTime, startTime) / constant.SECTION_MINUTES_LENGTH);
① 
`constant.SECTION_MINUTES_LENGTH`
↑これってなんで5分なの？
1分じゃダメなの？

② （①が1分じゃダメでセクションの概念が必要な場合）
`freeTime`じゃなくて`freeSections`とかどう？
`~Time`っていう変数名だと`startTime`とかと似てて長さ4の文字列に見えそう（将来読み返した時用）

2023-01-09 11:33 UTC, tom-takeru commented on app/helpers/schedule/simpleScheduleHelper.js
> +            let processTime = timeUtil.subtractTimeStr(plan.end_time, plan.start_time);
この`processTime`ってDBのカラムにあるけどTODOの時しか入ってないんだっけ？
それとも予定登録の時に`processTime`も計算して入れちゃう？

2023-01-09 11:33 UTC, tom-takeru commented on app/utils/time.js
> +};
同名でエクスポートするなら↓でいけると思う。
あえて書いていたならそれで了解👍
```JavaScript
module.exports = {
    compareTimeStr,
    subtractTimeStr,
    getStartAndEndTimeStr
};
```

2023-01-09 11:33 UTC, tom-takeru commented on app/test/helpers/schedule/simpleScheduleHelper.js
> +'use strict';
テストしてみたら通った👌

2023-01-09 11:33 UTC, tom-takeru commented on app/test/helpers/scheduleHelper.js
> +'use strict';
テスト通った👌

2023-01-09 11:33 UTC, tom-takeru commented on app/test/helpers/schedule/simpleScheduleHelper.js
> +            // return new Promise((resolve, reject) => {
このコメントアウトは？

2023-01-09 11:33 UTC, tom-takeru commented on app/test/helpers/schedule/simpleScheduleHelper.js
> +        it('should register 35m 1th TODO to schedule and does NOT register 60m 2th TODO to schedule.', async function () {
いくつかある序数のとこ
1th→1st
2th→2nd
3th→3rd
調べたら、話し言葉では今風の言い方として1thとかもあるらしい。

あと**should not** register 60m 2nd TODOのshouldが共通で省略してなくなるからdoesはいらない？
それかshould省略しないでdoesと置き換える？

2023-01-09 11:33 UTC, tom-takeru commented on app/helpers/schedule/simpleScheduleHelper.js
> + * @param {Array} todos - TODO
これ優先度降順のTODOだよね？
一応書いとく？
```
 * @param {Array} todos - 優先度降順のTODO
```

2023-01-09 11:33 UTC, tom-takeru commented on app/helpers/schedule/simpleScheduleHelper.js
> +            isError: true
`isError: true`のとき`errorId`とかって渡しといた方がどのエラーか特定できてデバック楽そう

2023-01-09 11:33 UTC, tom-takeru commented on app/helpers/schedule/simpleScheduleHelper.js
> +                    const divisionTodoCreateresult = await pool.query(
`Createresult`→`Create**R**esult`

2023-01-09 11:33 UTC, tom-takeru commented on app/helpers/schedule/simpleScheduleHelper.js
> +                    const divisionTodoCreateresult = await pool.query(
あと
`divisionTodo`よりも
`dividedTodo`の方が良い気がする

2023-01-09 11:33 UTC, tom-takeru commented on app/helpers/schedule/simpleScheduleHelper.js
> +function findAvailableTime(freeTime, sectionNum) {
どっちかというとメソッド名と引数の変数名は
`findAvailableSectionStartIndex(freeSection, sectionNum)`
っぽい気がする

2023-01-09 11:33 UTC, tom-takeru commented on app/helpers/schedule/simpleScheduleHelper.js
> +    let freeTime = new Array(timeUtil.subtractTimeStr(endTime, startTime) / constant.SECTION_MINUTES_LENGTH);
下を読んだ感じだと、4文字の時分文字列、分、セクションが混ざってそう。
変数名でパッと分かった方が後で読んだ時に良いと思う。

案）
`~_time`　　→4文字の時分文字列（DBのカラム名）
`~TimeStr`　→４文字の時分文字列
`~Min`　　　→分
`~Section`　→セクション
とか？

参考：https://remix-yh.net/301/

2023-01-09 11:33 UTC, tom-takeru commented on app/helpers/scheduleHelper.js
> +    const result = await scheduleLogic.execute(
`execute`部分も`try`の中でやれば`const scheduleLogic = ~`で行けそうだからそうしたい
（`let`だと書き変わりそうに見える）

2023-01-09 11:33 UTC, tom-takeru commented on app/test/utils/time.js
> +'use strict';
テスト通った👌

2023-01-10 10:46 UTC, Mellbrother commented on package.json
> +    "proxyquire": "^2.1.3",
単体対象でrequireするライブラリのモックを作るライブラリ

2023-01-10 10:50 UTC, Mellbrother commented on app/config/const.js
> +    SECTION_MINUTES_LENGTH: 5,
PLAN_TYPEは予定を示す番号が0だから、PLAN: 0にしてる
ロジックは1つ目のロジックがsimpleScheduleHelperだから、0: simpleScheduleHelperにしてる

2023-01-10 10:53 UTC, Mellbrother commented on app/helpers/schedule/simpleScheduleHelper.js
> +            let processTime = timeUtil.subtractTimeStr(plan.end_time, plan.start_time);
TODOの時は必須の認識で、予定はどっちでも良い

2023-01-10 10:54 UTC, Mellbrother commented on app/utils/time.js
> +};
明示的に書く方をよく見るからそのままにしようかな
同名ならそれでいけるんだね

2023-01-10 10:55 UTC, Mellbrother commented on app/test/helpers/schedule/simpleScheduleHelper.js
> +'use strict';
対応は不要でいいのかな？？

2023-01-10 10:55 UTC, Mellbrother commented on app/test/helpers/scheduleHelper.js
> +'use strict';
対応は不要でいいのかな？？

2023-01-10 10:57 UTC, Mellbrother commented on app/test/helpers/schedule/simpleScheduleHelper.js
> +        it('should register 35m 1th TODO to schedule and does NOT register 60m 2th TODO to schedule.', async function () {
@tom-takeru 
難しい
会議で説明頼む

2023-01-21 05:09 UTC, tom-takeru commented on package.json
> +    "proxyquire": "^2.1.3",
会議で説明欲しいかも

2023-01-21 05:18 UTC, tom-takeru commented on app/test/helpers/schedule/simpleScheduleHelper.js
> +        it('should register 35m 1th TODO to schedule and does NOT register 60m 2th TODO to schedule.', async function () {
#### メモ
1stはfirst
2ndはsecond
3rdはthird

全部省略しないで書くと、、、
`should register 35m 1st TODO to schedule and should NOT register 60m 2nd TODO to schedule.`
2つ目の`should`を省略すると、、、
`should register 35m 1st TODO to schedule and NOT register 60m 2nd TODO to schedule.`

↑この2文のどっちかが良い

2023-01-22 06:10 UTC, Mellbrother commented on app/utils/time.js
> + *  予定の開始時間・終了時間を計算する
以下の感じでも良い？
helper : コントローラーごとの特有の処理
utility : いろんなコントローラーで使用する可能性がある

↑で問題なければ、今回はutility

2023-01-22 06:12 UTC, Mellbrother commented on app/helpers/schedule/simpleScheduleHelper.js
> +    // TODO: バリデーション
- [ ] コメント削除

2023-01-22 06:13 UTC, Mellbrother commented on app/utils/time.js
> + * @returns {number} - 開始時間、終了時間
- [ ] jsDoc修正

2023-01-22 06:14 UTC, Mellbrother commented on app/utils/time.js
> +        now.getDate(),
- [ ] 変数に入れる

2023-01-22 06:14 UTC, Mellbrother commented on app/utils/time.js
> + * @returns {number} - 比較結果
- [ ] 単位を追加

2023-01-22 06:17 UTC, Mellbrother commented on app/helpers/scheduleHelper.js
> +    const result = await scheduleLogic.execute(
- [ ] try の中に入れる

2023-01-22 06:18 UTC, Mellbrother commented on app/helpers/schedule/simpleScheduleHelper.js
> +                    const divisionTodoCreateresult = await pool.query(
- [ ] dividedTodoに変更

2023-01-22 06:19 UTC, Mellbrother commented on app/helpers/schedule/simpleScheduleHelper.js
> +            isError: true
- [ ] errorIdなどを追加

2023-01-22 06:19 UTC, Mellbrother commented on app/helpers/schedule/simpleScheduleHelper.js
> + * @param {Array} todos - TODO
- [ ] コメントを修正

2023-01-22 06:20 UTC, Mellbrother commented on app/test/helpers/schedule/simpleScheduleHelper.js
> +            // return new Promise((resolve, reject) => {
- [ ] 不要なコメント削除

2023-01-22 06:37 UTC, Mellbrother commented on app/test/helpers/schedule/simpleScheduleHelper.js
> +        it('should register 35m 1th TODO to schedule and does NOT register 60m 2th TODO to schedule.', async function () {
テスト用のコメントだから、誤解生むような文章でなければそのままでいいと思ったりしてる。。。

should register 35m 1st TODO to schedule and NOT register 60m 2nd TODO to schedule.
の方が個人的にはいいかな

2023-01-22 06:41 UTC, Mellbrother commented on app/helpers/schedule/simpleScheduleHelper.js
> +function findAvailableTime(freeTime, sectionNum) {
- [ ] 関数名を修正

2023-01-22 06:49 UTC, Mellbrother commented on app/helpers/schedule/simpleScheduleHelper.js
> +    let freeTime = new Array(timeUtil.subtractTimeStr(endTime, startTime) / constant.SECTION_MINUTES_LENGTH);
①
1分でも良い。
一旦パフォーマンスを考えて5分にしてる

②
変数名はfreeSectionsに変更


他も提案いただいた感じで変数名修正

2023-01-26 10:36 UTC, tom-takeru commented on app/utils/time.js
> + *  予定の開始時間・終了時間を計算する
開発ルール更新しとくねー

2023-01-26 13:49 UTC, tom-takeru commented on app/helpers/schedule/simpleScheduleHelper.js
> +}
for一重で書いてみた
パフォーマンス問題でそうならちょっとこっちの方が良いと思う

```js
function findAvailableSectionStartIndex(freeSections, sectionNum) {
    for (let i = 0; i < freeSections.length; i++) {
        if (freeSections.length - i < sectionNum) {
            break;
        }
        const checkSections = freeSections.slice(i, i + sectionNum);
        const nextCheckSectionsStartIndex = checkSections.lastIndexOf(1);
        if (nextCheckSectionsStartIndex !== -1) {
            i += nextCheckSectionsStartIndex;
        } else {
            return i;
        }
    }
    return -1;
}
```

2023-01-26 14:16 UTC, tom-takeru commented on app/helpers/schedule/simpleScheduleHelper.js
> +    let freeSectionsSum = freeSections.length * constant.SECTION_MINUTES_LENGTH;
これドットかっていうと`freeTimeMinSum`な感覚なんだけどどう？

2023-01-26 14:30 UTC, tom-takeru commented on app/helpers/schedule/simpleScheduleHelper.js
> + * @param {Array} todos - 優先度降順のTODO
これ前で指摘しといて申し訳ないんだけど、優先度降順にするのってこのヘルパーの役割ではないんだっけ？

2023-01-26 14:36 UTC, tom-takeru commented on app/helpers/schedule/simpleScheduleHelper.js
> + * @param {Array} todos - 優先度降順のTODO
呼び出し元見たかんじだと特に並び替えてないから、todoの優先度もパラメータとしてもらうようにしてその順に並び替えないといけない？

2023-01-26 14:53 UTC, tom-takeru commented on app/helpers/schedule/simpleScheduleHelper.js
> + * @param {Array} todos - 優先度降順のTODO
めちゃくちゃ根本的なこと言うと、

- TODO登録時点に、TODOが予定の隙間に入る
- 予定表部分にあるTODOを押すと、TODO一覧に戻る
- TODO一覧部分にあるTODOを押すと、TODOが予定の隙間に入る

っていう設計方針でもよかったのかもね、、、。
今からでもあり？

2023-01-27 00:15 UTC, tom-takeru commented on app/helpers/schedule/simpleScheduleHelper.js
> +}
chatGPTにも最適化させてみた

以下のように最適化することができます。

```js
function findAvailableSectionStartIndex(freeSections, sectionNum) {
    let count = 0;
    for (let i = 0; i < freeSections.length; i++) {
        if (freeSections[i] === 0) {
            count++;
        } else {
            count = 0;
        }
        if (count === sectionNum) {
            return i - count + 1;
        }
    }
    return -1;
}
```
上記のコードでは、双重のループを使用する必要がなくなり、かつ、見つかった場合に直ちに結果を返すことができるため、処理が高速化されます。

2023-01-28 01:38 UTC, tom-takeru commented on app/utils/time.js
> + * @returns {number} - 開始時間、終了時間
これやってない？

2023-01-28 01:49 UTC, tom-takeru commented on app/helpers/scheduleHelper.js
> +            isError: true
これはもう理解不能のエラーなんだよね？
ただここでcatchしたエラーってことはわかった方が良いと思う。
エラーIDとエラーメッセージを決めて入れる時に忘れないように、`errorId`と`errorMessage`は入れとく？

2023-01-28 01:51 UTC, tom-takeru commented on app/utils/time.js
> + * @returns {string} result.endTime   - 終了時間(書式:hhmm)
書き直しといた！

2023-01-28 01:52 UTC, tom-takeru requested changes
コメントした！
1回目のレビューで指摘できなくてごめん🙏

2023-01-28 02:04 UTC, tom-takeru commented on app/helpers/schedule/simpleScheduleHelper.js
> +    let freeSectionsSum = freeSections.length * constant.SECTION_MINUTES_LENGTH;
ChatGPT
```
Q:
残りの自由な時間(分)をローワーキャメルケースの変数名にして欲しい

A:
remainingFreeTimeInMinutes
```

2023-01-29 07:14 UTC, Mellbrother commented on app/helpers/schedule/simpleScheduleHelper.js
> + * @param {Array} todos - 優先度降順のTODO
DBに入っている状態が既に降順になっているはずだから、並び替えは不要
TODOがスケジュール化されてもTODOであることは変わらないから、特に問題ないのでは？

2023-01-29 07:17 UTC, Mellbrother commented on app/helpers/schedule/simpleScheduleHelper.js
> +    let freeSectionsSum = freeSections.length * constant.SECTION_MINUTES_LENGTH;
空いてるセクション（freeTimeSection）の合計値（sum）で特にわかりにくくないと思うんだけど、わかりにくい？
名前を似せておいた方が関連性があるってこともわかっていいと思う（名前が分かりにくすぎる場合は別だけど）

2023-01-29 07:24 UTC, Mellbrother commented on app/helpers/schedule/simpleScheduleHelper.js
> +}
修正した
Chat GPT頭いいな

2023-01-29 07:24 UTC, Mellbrother commented on app/helpers/scheduleHelper.js
> +            isError: true
入れた

2023-01-30 00:35 UTC, tom-takeru commented on app/helpers/schedule/simpleScheduleHelper.js
> +    let freeSectionsSum = freeSections.length * constant.SECTION_MINUTES_LENGTH;
freeSectionsSumっていう変数名から、
空いてるセクションの合計[単位:セクション数]
って思ったな

似せるのにはもちろん賛成だけどSectionsって入ってるとセクション数が単位だと思っちゃうからそこは似せないほうが良いと思う。
似せるのはFreeの部分だけで良いんじゃないかな？

けいすけがremainingFreeTimeMinで分かるんだったらこっちにしたいな

このブランチから伸びてるブランチをリベースする手間はわかってるから、別チケ俺に振ってくれればどっかでやるよ。

2023-01-31 11:14 UTC, tom-takeru commented on app/helpers/schedule/simpleScheduleHelper.js
> + * @param {Array} todos - 優先度降順のTODO
> DBに入っている状態が既に降順になっているはずだから、並び替えは不要

`todo_orders`テーブルに入ってる優先度情報をもとにTODOをスケジュールに挟まないといけないと思う

そう思う理由は↓かな

- PostgreSQLは（多分他のDBも）`select`で`order by`を指定しないと並び順は保証されない
  - [PostgreSQLのorder byに関するドキュメント](https://www.postgresql.jp/document/13/html/sql-select.html#:~:text=order%20by%E3%81%8B%E3%82%99%E6%8C%87%E5%AE%9A%E3%81%95%E3%82%8C%E3%81%AA%E3%81%84%E5%A0%B4%E5%90%88%E3%81%AF%E3%80%81%E3%82%B7%E3%82%B9%E3%83%86%E3%83%A0%E3%81%8B%E3%82%99%E8%A8%88%E7%AE%97%E9%81%8E%E7%A8%8B%E3%81%A6%E3%82%99%E8%A6%8B%E3%81%A4%E3%81%91%E3%81%9F%E9%A0%86%E7%95%AA%E3%81%A6%E3%82%99%E8%A1%8C%E3%81%8B%E3%82%99%E8%BF%94%E3%81%95%E3%82%8C%E3%81%BE%E3%81%99%20(%E5%BE%8C%E8%BF%B0%E3%81%AEorder%20by%20clause%E3%82%92%E5%8F%82%E7%85%A7%E3%81%97%E3%81%A6%E3%81%8F%E3%81%9F%E3%82%99%E3%81%95%E3%81%84)%E3%80%82)にも書いてある
- `order by`を指定しようとしても、`plans`テーブルには並び替え用カラムはない
  - `todo_orders`でTODOの優先度を管理してる

---

> TODOがスケジュール化されてもTODOであることは変わらないから、特に問題ないのでは？

どっかで必ず、「スケジュール化したTODOのIDを`todo_orders`テーブルから消す」っていう処理が必要になると思う
そうしないと`todo_orders`のに入ってる優先度順のカンマ区切りの文字列がどんどん大きくなっちゃう

`todo_orders`テーブルは
「今あるスケジュール化されてないTODOの優先度」
っていう定義で管理しない？

スケジュール化のタイミングで`todo_orders`テーブルから、
スケジュールに入ったTODOを消すのが自然なんじゃないかな？

`todo_orders`テーブルが後から「必要だ」ってなって入れたから、
その話があんまり設計書にないよね、、、先に決めとくべきだったのに申し訳ない、、、。

2023-02-01 11:06 UTC, Mellbrother commented on app/helpers/schedule/simpleScheduleHelper.js
> + * @param {Array} todos - 優先度降順のTODO
あんまりわからないから、会議でよろしく〜

2023-02-01 11:14 UTC, Mellbrother commented on app/helpers/schedule/simpleScheduleHelper.js
> + * @param {Array} todos - 優先度降順のTODO
> todo_ordersテーブルに入ってる優先度情報をもとに、TODOをスケジュールに挟まないといけないと思う
TODOに挟み込むのところがよくわからない

> スケジュール化したTODOのIDをtodo_ordersテーブルの優先度csvから消す
csvって何だろう？
どこかで消すのは必要だと思うけど、スケジュール化されたタイミングではないと思ってる。
前聞いた話では、TODOがスケジュール化されたかに関係なくtodo_ordersで並び順管理するって感じだった気がする

2023-02-01 11:16 UTC, Mellbrother commented on app/helpers/schedule/simpleScheduleHelper.js
> + * @param {Array} todos - 優先度降順のTODO
todo_ordersの更新は一旦ここの処理と直接関係ないから、別チケット対応でいい？

2023-02-01 11:16 UTC, Mellbrother commented on app/helpers/schedule/simpleScheduleHelper.js
> +    let freeSectionsSum = freeSections.length * constant.SECTION_MINUTES_LENGTH;
修正した

2023-02-01 11:57 UTC, tom-takeru approved these changes
LGTM

2023-02-01 11:57 UTC, tom-takeru approved these changes
LGTM

2023-02-01 11:58 UTC, merged