スケジュールセッティング処理実装
daydule/backend pull request #24
Opened 2023-01-08 06:30 UTC by Mellbrother

# 事前確認

-   [x] PR前に動作確認をしたか
-   [x] ビルドエラー/ESLintエラーは起きていないか
-   [x] [開発ルール](https://daydule.atlassian.net/wiki/spaces/DAYDULE/pages/9765029)を守って実装しているか
-   [ ] 単体テストが全てOKになっているか
-   [x] 機密情報を含んでいないか
-   [x] 最新の`develop`ブランチを反映しているか

# やったこと
スケジュールセッティング参照機能実装

# やらないこと
特になし

# 懸念点や注意点
特になし

# その他
特になし

2023-01-09 11:39 UTC, tom-takeru commented on app/controllers/user.js
> +    const dayListNum = constant.DAY_LIST_NUM;
これって↓じゃだめなの？
```js
const dayListLength = constant.DAY_LIST.length
```

2023-01-09 11:52 UTC, tom-takeru commented on app/controllers/user.js
> +    const daySettingInfo = [];
`try`の中だけで使ってそうだからスコープを`try`の中に持っていきたい

2023-01-09 11:57 UTC, tom-takeru requested changes
コメント書いた！

2023-01-10 09:30 UTC, Mellbrother commented on app/controllers/user.js
> +    const dayListNum = constant.DAY_LIST_NUM;
修正した

2023-01-10 09:30 UTC, Mellbrother commented on app/controllers/user.js
> +    const daySettingInfo = [];
修正した

2023-01-21 05:02 UTC, tom-takeru approved these changes
LGTM👌

2023-01-21 05:02 UTC, merged