DAYD-951 繰り返し予定の登録APIの修正および繰り返し予定の参照APIの追加
daydule/backend pull request #82
Opened 2023-10-22 10:02 UTC by atoook

# 事前確認

-   [ ] PR前に動作確認をしたか
-   [ ] ビルドエラー/ESLintエラーは起きていないか
-   [ ] [開発ルール](https://daydule.atlassian.net/wiki/spaces/DAYDULE/pages/9765029)を守って実装しているか
-   [ ] 単体テストが全てOKになっているか
-   [ ] 機密情報を含んでいないか
-   [ ] 最新の`develop`ブランチを反映しているか

# レビュワーによる動作確認

- [ ] @Mellbrother 
- [ ] @tom-takeru 

# やったこと
- 繰り返し予定の登録API（/recurringPlan/create）について
-- day_idをday_settingsテーブルから取得するよう修正  
- 繰り返し予定の参照API（/recurringPlan/read）について
-- recurring_plansテーブルからログインユーザが登録済のレコードを全件取得するAPIを追加

# やらないこと
- 以下のチケット対応の「更新・削除」のケースは本チケットでは対応しない。
- https://daydule.atlassian.net/browse/DAYD-741?atlOrigin=eyJpIjoiZmQyNTM2ZWU4MDgyNDYyOTg4NzQyMDQ2M2M5NmI4ZDUiLCJwIjoiaiJ9
※今回の修正で、登録APIではログインユーザのday_idを取得するようにしたため他ユーザの定期予定が登録されることはない。

# 懸念点や注意点
- 繰り返し予定の参照API（/recurringPlan/read）について
-- 現状は、「recurring_plansテーブル」の全カラムを取得するようにしています。
もし繰り返し予定を画面で表示する際に、ユーザが登録しているスケジュールの開始、終了時刻に応じてスケジュール表を表示する時間帯を変化させる場合はinner joinしているdaysettings.schedule_start_time/schedule_end_timeもこのapiで取得した方が良いと思っています。
この点について、ご意見・ご指摘あれば伺いたいです。
-- validaterには「guestCheck」を指定していますが、これで十分か確認いただきたいです。

# その他
特になし

2023-10-22 10:12 UTC, atoook commented on app/controllers/recurringPlan.js
> +        await client.query('BEGIN');
この行は後のコミットで削除済です

2023-10-22 12:42 UTC, Mellbrother commented
> 現状は、「recurring_plansテーブル」の全カラムを取得するようにしています。
> もし繰り返し予定を画面で表示する際に、ユーザが登録しているスケジュールの開始、終了時刻に応じてスケジュール表を表示する時間帯を変化させる場合はinner joinしているdaysettings.schedule_start_time/schedule_end_timeもこのapiで取得した方が良いと思っています。
> この点について、ご意見・ご指摘あれば伺いたいです。

検討ありがとうございます。
繰り返し予定の画面で曜日ごとの開始時間、終了時間、スケジュール作成ロジックを更新できるようにする予定なので、それらの情報も含めていただけますでしょうか？

2023-10-22 12:42 UTC, Mellbrother commented on app/controllers/recurringPlan.js
> +        const daySettingsInfo = [];
daySettingsでいい気がしました

2023-10-22 12:42 UTC, Mellbrother commented on app/controllers/recurringPlan.js
> +router.get('/read', guestCheck, async function (req, res) {
app.jsのguestCheckより強力なloginCheckをしているので、ここでのチェックは不要です
バリデーションは後で追加ということかと思いましたので、TODOコメントだけ追加お願いできますでしょうか？

2023-10-22 12:42 UTC, Mellbrother commented on app/controllers/recurringPlan.js
> +            recurringPlanInfo: result
recurringPlansでいいと思いました

2023-10-28 01:57 UTC, atoook commented on app/controllers/recurringPlan.js
> +        const daySettingsInfo = [];
修正しましたので確認お願いします。

2023-10-28 01:57 UTC, atoook commented on app/controllers/recurringPlan.js
> +router.get('/read', guestCheck, async function (req, res) {
コメント追加しましたので確認お願いします。

2023-10-28 01:57 UTC, atoook commented on app/controllers/recurringPlan.js
> +            recurringPlanInfo: result
修正しましたので確認お願いします。

2023-10-31 13:30 UTC, Mellbrother commented on app/controllers/recurringPlan.js
> +router.get('/read', guestCheck, async function (req, res) {
@atoook 
guestCheck不要なので、削除お願いします〜

2023-11-01 12:29 UTC, atoook commented on app/controllers/recurringPlan.js
> +router.get('/read', guestCheck, async function (req, res) {
対応しました！

2023-11-04 03:01 UTC, tom-takeru requested changes
コメントいくつかしました！
確認をお願いします！

2023-11-04 03:01 UTC, tom-takeru commented on app/controllers/recurringPlan.js
> +router.get('/read', guestCheck, async function (req, res) {
↓こういうことじゃやないですかね？

```suggestion
router.get('/read', async function (req, res) {
```

2023-11-04 03:01 UTC, tom-takeru commented on app/controllers/recurringPlan.js
> +    // TODO: バリデーションは後で追加
バリデーション(同ファイル内のdeleteRecurringPlanValidatorsのようなミドルウェア)を今回実装しない場合は、TODOコメントではなく、Jiraで別チケット起票が良いと思います！

```suggestion
```

2023-11-04 03:01 UTC, tom-takeru commented on app/controllers/recurringPlan.js
> +            recurringPlans: result
- SQLの取得はそのまま
- day_settingsテーブルの情報は別の大きさ7（日〜土）のdaySettingsという名前の別オブジェクトで返す
というのはどうでしょうか？

↑をするとSQLの呼び出し回数はそのままでAPIが使いやすくなる&理解しやすくなると思いました！🐊

2023-11-04 03:01 UTC, tom-takeru commented on app/controllers/recurringPlan.js
> +            'SELECT rp.*, ds.day, ds.schedule_start_time, ds.schedule_end_time, ds.scheduling_logic FROM recurring_plans rp INNER JOIN day_settings ds ON rp.day_id = ds.id WHERE ds.user_id = $1;',
### daydule/backendの実装方針について相談

「パフォーマンスを意識して、SQL発行回数を減らすように努力した実装にする」というものを追加するかどうか？

2023-11-04 03:07 UTC, tom-takeru commented on app/controllers/recurringPlan.js
> +    // TODO: バリデーションは後で追加
よくよく見ると、バリデーション不要＆チケット起票不要でした。
このAPIはuserIdしかリクエストパラメータにない＆userIdは勝手にバックエンドで付与されるパラメータなのでバリデーションいらないです。

2023-11-08 13:31 UTC, tom-takeru commented on app/controllers/recurringPlan.js
> +            'SELECT rp.*, ds.day, ds.schedule_start_time, ds.schedule_end_time, ds.scheduling_logic FROM recurring_plans rp INNER JOIN day_settings ds ON rp.day_id = ds.id WHERE ds.user_id = $1;',
### 話したこと

以下の方針で行く。

- パフォーマンスを意識して、SQL発行回数を減らすように努力した実装にする
- apiの戻り値となるjsonのオブジェクトは整える

2023-11-22 13:42 UTC, atoook commented on app/controllers/recurringPlan.js
> +router.get('/read', guestCheck, async function (req, res) {
こちら対応しました。

2023-11-22 13:43 UTC, atoook commented on app/controllers/recurringPlan.js
> +    // TODO: バリデーションは後で追加
対応しました。

2023-11-22 13:44 UTC, atoook commented on app/controllers/recurringPlan.js
> +            recurringPlans: result
day_settingsテーブルの情報は別の大きさ7（日〜土）のdaySettingsという名前の別オブジェクトに整形し直して返すように修正しました。

2023-11-22 13:46 UTC, atoook commented on app/controllers/recurringPlan.js
> +            'SELECT rp.*, rp.id as recurring_plans_id, ds.id as day_settings_id, ds.day, ds.schedule_start_time, ds.schedule_end_time, ds.scheduling_logic FROM recurring_plans rp RIGHT OUTER JOIN day
recurring_plansのidをdaysettingsのオブジェクトに含めたかったため、reccuring_plans_idというエイリアスをつけて取得するようにしました。

2023-11-22 13:51 UTC, atoook commented on app/controllers/recurringPlan.js
> +        const recurringPlansResult = formatUtils.sliceObjectStEd(result, 0, -6).filter((obj) => obj.id != null);
- オブジェクトの配列をスライスする処理をユーティリティとして切り分けました。使用法は配列のスライスと同じです。
- recurring_plansに対してday_settingsをright outer join しているので、繰り返し予定が存在しない曜日がある際に、recurring_plansの各カラムの値はnullになります。このnullを除外するために.filterでidがnullのオブジェクトを取り除くようにしています。

2023-11-22 13:54 UTC, atoook commented on app/controllers/recurringPlan.js
> +            delete daySetting.daySettingsId;
selectする際は、recurringPlansIdとして取得していたday_settingsのidを、テーブル定義と合わせてidとして返すようにしています。

2023-11-25 23:08 UTC, tom-takeru requested changes
たくさんコメントを書いてしまいました。すみません 🙏 
確認をお願いします！

2023-11-25 23:08 UTC, tom-takeru commented on app/utils/formatApiResponse.js
> +            .reduce((sliced, key) => {
処理がオブジェクトのキー順序に依存している点が、あまり良くないように感じました。
今は改善している可能性もありますが、[少なくとも過去はこんな挙動](https://qiita.com/suguru03/items/bf48610225fefcb0f45e)だったので可読性を考えると勘違いしてしまう可能性があると思います。

以下のような関数を用意して呼び出し元で整形するのはどうでしょうか？そうすれば、`sliceObjectStEd `と`sliceObjectSt`を用意しなくても済むと思います！
（ChatGPTに書いてもらいました 🐊 ）

```
/**
 * 指定されたキーに基づいてオブジェクトのプロパティをフィルタリングし、
 * 新しいオブジェクトの配列を作成して返します。配列内の各オブジェクトから、
 * 指定されたキーに一致するプロパティのみが含まれる新しいオブジェクトが生成されます。
 *
 * @param {Object} obj - フィルタリングされるオブジェクト
 * @param {Array<string>} keys - 抽出するキーの配列
 * @returns {Object} - フィルタリングされたオブジェクト
 */
function filterObjectByKey(obj, keys) {
    return keys.reduce((filteredObj, key) => {
        if (obj.hasOwnProperty(key)) {
            filteredObj[key] = obj[key];
        }
        return filteredObj;
    }, {});
}

// ユーザー情報の配列
const users = [
  { id: 1, name: 'Alice', email: 'alice@example.com', age: 25 },
  { id: 2, name: 'Bob', email: 'bob@example.com', age: 30 },
  { id: 3, name: 'Carol', email: 'carol@example.com', age: 22 }
];

// 特定のキー（name と email）のみを抽出
const filteredUsers = users.map(user => filterObjectByKey(user, ['name', 'email']));

console.log(filteredUsers);
```

2023-11-25 23:08 UTC, tom-takeru commented on app/utils/formatApiResponse.js
中に入っている関数を考えると、すこし限定的すぎるファイル名に感じました！
私が16行目へのコメントで提案している`filterObjectByKey`関数のみがこのファイルに入る場合は↓のようなファイル名はどうでしょうか？

```
この関数を含むファイルをutilフォルダに配置する場合、ファイルの内容とその目的を反映する名前を選ぶことが重要です。filterObjectByKey関数は、オブジェクトのプロパティをフィルタリングするユーティリティ機能を提供しますので、ファイル名もそれに沿ったものが適切です。

考えられるファイル名の例は以下の通りです：

objectFilters.js
propertyFilter.js
keyBasedFilter.js
filterUtils.js
これらの名前は、ファイルがオブジェクトのキーに基づくフィルタリング機能を提供することを明確に示しています。プロジェクトの命名規則や既存のファイル構成に合わせて、最も適切な名前を選択してください。例えば、他の類似のユーティリティ関数がすでにutilフォルダ内に存在する場合、その命名スタイルに合わせると良いでしょう。
```

2023-11-25 23:08 UTC, tom-takeru commented on app/controllers/recurringPlan.js
> +            'SELECT rp.*, rp.id as recurring_plans_id, ds.id as day_settings_id, ds.day, ds.schedule_start_time, ds.schedule_end_time, ds.scheduling_logic FROM recurring_plans rp RIGHT OUTER JOIN day
ある一つの曜日設定のプロパティの名前なので　`as day_setting_id`　の方が良いのかなと思いました！ 🐊

2023-11-25 23:08 UTC, tom-takeru commented on app/controllers/recurringPlan.js
> +        const uniqueDaySettingsResult = Array.from(new Set(daySettingsResult.map(JSON.stringify)), JSON.parse);
この部分に関してこんな感じで実装できそうな気がしました！どうでしょうか？
（エアーコーディングなので、実際に動かしたりしていないです！雰囲気だけ見ていただけたら🐊）

```
// NOTE: 曜日ごとに繰り返し予定のidを集計して大きさ7の配列に変換する
const groupedDaySettings = daySettingsResult.reduce((acc, daySetting) => {
    const daySettingIndex = acc.findIndex(obj => obj.day === daySetting.day)
    if (daySettingIndex === -1) {
        acc.push({ 
            id: daySetting.id,
            day: daySetting.day,
            startTime: daySetting.startTime,
            endTime: daySetting.endTime,
            schedulingLogic: daySetting.schedulingLogic
            recurringPlanIds: [daySetting.recurringPlanId]
        });
    } else {
        acc[daySettingIndex].recurringPlanIds.push(daySetting.recurringPlanId);
    }
}, []);
```

2023-11-28 00:41 UTC, tom-takeru commented
@atoook 
DAYD-1000のPRが先にGitHub上（リモートブランチ）でこのPRのブランチにマージされてしまったので、変更する際は先にPullしないとちょっとめんどくさくなってしまう気がしています！お気をつけて！

2023-12-02 03:34 UTC, tom-takeru approved these changes, later dismissed
LGTM 🧶 
動作確認したらマージしちゃいます！

2023-12-03 02:59 UTC, tom-takeru approved these changes
動作確認していて少し気になった部分があったのでコミットしてしまいました！
@atoook さんにも動作確認していただいて、よければ動作確認OKのコメントを残してマージしてしまってください！

2023-12-03 02:59 UTC, tom-takeru commented on app/controllers/recurringPlan.js
> +                    recurringPlanIds: [daySetting.id]
<img width="423" alt="image" src="https://github.com/daydule/backend/assets/57748294/635369c6-2565-423c-951e-3a76875970e8">

コードを提案した時に気づけなくて申し訳ないのですが、繰り返し予定が一つもない曜日の`daySetting`オブジェクトの`recurringPlanIds`が`null`を一つの要素として持つ大きさ1の配列になってしまっています。

`recurringPlanIds: null`となる方が良いと思ったので、この辺りを修正していただいても良いですか？

2023-12-03 02:59 UTC, tom-takeru commented on app/controllers/recurringPlan.js
> +                    recurringPlanIds: [daySetting.id]
簡単な修正だったのでやってしまいました！
- [x] 繰り返し予定が一つもない曜日のdaySettingオブジェクトのrecurringPlanIdsプロパティがnullになるように修正
- [x] （ついで）daySettingsの順番が曜日順になるように修正

2023-12-03 06:56 UTC, atoook commented on app/controllers/recurringPlan.js
> +                    recurringPlanIds: [daySetting.id]
@tom-takeru さん
確かに`recurringPlanIds: nullとなる方が良い`ですね。
細かいところまで、ありがとうございます！
動作確認したのでマージします。

2023-12-03 06:57 UTC, merged