Feature/dayd 1000
daydule/backend pull request #83
Opened 2023-10-28 02:00 UTC by atoook

# 事前確認

-   [ ] PR前に動作確認をしたか
-   [ ] ビルドエラー/ESLintエラーは起きていないか
-   [ ] [開発ルール](https://daydule.atlassian.net/wiki/spaces/DAYDULE/pages/9765029)を守って実装しているか
-   [ ] 単体テストが全てOKになっているか
-   [ ] 機密情報を含んでいないか
-   [ ] 最新の`develop`ブランチを反映しているか

# レビュワーによる動作確認

- [ ] @Mellbrother 
- [ ] @tom-takeru To

# やったこと
- 定期予定の更新、削除時の条件にログインユーザのユーザidを追加し、誤って他ユーザの定期予定が更新・削除されないようにしました。

# やらないこと
- SQLのみの修正のため、バリデーションの修正はしていません。

# 懸念点や注意点
特になし

# その他
特になし

2023-10-31 13:40 UTC, Mellbrother reviewed
@atoook 
OKだと思います
動作確認はフロントできた後で良いですかね？？

2023-11-04 04:35 UTC, tom-takeru requested changes
コメントしました！
確認をお願いします 🙏

2023-11-04 04:35 UTC, tom-takeru commented on app/controllers/recurringPlan.js
> +        daySettings.push(...daySettingsResult.rows);
↓こんな雰囲気で書けないですかね？　配列で初期化しなくても良いように思えました　🐊 
```
const daySettingsResult = await dbHelper.query(client, 'SELECT id FROM day_settings WHERE user_id = $1', [userId]);
const daySettings = daySettingsResult.rows;
```

2023-11-22 14:18 UTC, atoook commented on app/controllers/recurringPlan.js
> +        daySettings.push(...daySettingsResult.rows);
指摘いただいた通り対応しました。

2023-11-25 23:11 UTC, tom-takeru approved these changes
🍨

2023-11-27 14:48 UTC, Mellbrother approved these changes

2023-11-27 14:48 UTC, merged